{% set version = "0.7.2.888" %}
{% set lib_version = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2]+".0" %}
{% set soname = version.split(".")[0] %}
{% set arm_variant_type = arm_variant_type | default("sbsa") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}

package:
  name: libcusolvermp-split
  version: {{ version }}

source:
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-x86_64/libcusolvermp-linux-x86_64-{{ version }}_cuda12-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "70243423e07861007ca5a95d35247af4ecdbcd0bf77aa09016a1abf3dcffb6a8"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-x86_64/libcusolvermp-linux-x86_64-{{ version }}_cuda13-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "5b7ac5f41e0f2d0ddb226736879c1ad123302d08e4dbccb543dad2c90780888d"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-sbsa/libcusolvermp-linux-sbsa-{{ version }}_cuda12-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "4c1a2688ec0072dec6d9d2303b489a48ad34a419e42ba05f51af68a43221fed6"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-sbsa/libcusolvermp-linux-sbsa-{{ version }}_cuda13-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "429772ba439da9ac1ea88989a0cc56f2f14b377af349129b1bf913e9357dbbd8"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]

build:
  number: 2
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None") or (cuda_compiler_version or "").startswith("11")]
  script:
    - cp -rv include $PREFIX
    - cp -rv lib $PREFIX
    - check-glibc "$PREFIX"/lib*/*.so.* "$PREFIX"/bin/* "$PREFIX"/targets/*/lib*/*.so.* "$PREFIX"/targets/*/bin/*  # [linux]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:
  - name: libcusolvermp{{ soname }}
    build:
      run_exports:
        - {{ pin_subpackage("libcusolvermp" ~ soname, max_pin="x.x") }}
      ignore_run_exports_from:
        - libcusolver-dev
        - cuda-cudart-dev
        - libcublas-dev
      ignore_run_exports:
        # Ignore `cuda-version` constraint as this supports CUDA Enhanced Compatibility.
        - cuda-version
    files:
      - lib/libcusolverMp.so.*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64]
      host:
        - cuda-version {{ cuda_compiler_version }}
        - libcusolver-dev
        - cuda-cudart-dev
        - libcublas-dev
        - nccl 2.25.*  # [(cuda_compiler_version or "").startswith("12")]
        - nccl 2.27.*  # [(cuda_compiler_version or "").startswith("13")]
      run:
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
        - libcusolver
        - cuda-cudart
        - libcublas
    test:
      commands:
        - test -L $PREFIX/lib/libcusolverMp.so.{{ soname }}
        - test -f $PREFIX/lib/libcusolverMp.so.{{ lib_version }}

  - name: libcusolvermp-dev
    build:
      ignore_run_exports:
        - cuda-version
      run_exports:
        - {{ pin_subpackage("libcusolvermp" ~ soname, max_pin="x.x") }}
    files:
      - lib/libcusolverMp.so
      - include/cusolverMp.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64]
      run:
        - {{ pin_subpackage("libcusolvermp" ~ soname, exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/cusolverMp.h
        - test -L $PREFIX/lib/libcusolverMp.so

about:
  home: https://docs.nvidia.com/cuda/cusolvermp/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cusolvermp/license/index.html
  summary: NVIDIA cuSOLVERMp is a high-performance, distributed-memory, GPU-accelerated library that provides tools for the solution of dense linear systems and eigenvalue problems.
  description: |
    NVIDIA cuSOLVERMp is a high-performance, distributed-memory, GPU-accelerated library that provides tools for the solution of dense linear systems and eigenvalue problems.
    cuSOLVERMp is compatible with 2D block-cyclic data layout and provides ScaLAPACK-like C APIs.
  doc_url: https://docs.nvidia.com/cuda/cusolvermp/

extra:
  feedstock-name: libcusolvermp
  recipe-maintainers:
    - conda-forge/cuda
